### ISSUE TITLE
Implement "archive" and "bin" lists alongside "active" list

### ISSUE THREAD

**Issue by mattheuslee** [CS2103JUN2017-T2/main#53]

**Comment by ChuaPingChan** [comment]
![modelclassdiagram](https://user-images.githubusercontent.com/29548741/27984399-cb3f4a60-6407-11e7-99a1-1ab9f182daef.png)

@CS2103JUN2017-T2/developers 
Hi all, this is the updated Model class diagram. Since the last one, I realised it's necessary to have 3 new filtered lists (i.e. `ActiveList`, `DeadlineList` and `FloastingTaskList`) to be binded with the GUI panels.

**Comment by ChuaPingChan** [comment]
![modelclassdiagram](https://user-images.githubusercontent.com/29548741/27995559-1ab53bb2-6503-11e7-8dbd-b58bf01da40a.png)

@CS2103JUN2017-T2/developers 
Hi all, this is the latest model class diagram. I've merged `ActiveList`, `Archive` and `Bin` into a class called `MiscEntryList` because they all actually have the same behavior.

**Comment by ChuaPingChan** [comment]
@CS2103JUN2017-T2/developers 
I have already implemented all the classes. Most of the lower-level classes (e.g. `Event`, `Deadline`, `FloatingTask`, `EventList`, `DeadlineList`) have been unit-tested but I've not finished testing the higher-level classes yet (i.e. `ModelManager` and `EntryBook`). I'm still in the process of editing some test utilities and stubs to make testing these high-level classes easier to test less dependent on the lower-level classes. Even so, these interfaces and classes that specify model's API are ready for you to refer to already:
1. `Model`
2. `ReadOnlyEntryBook`
3. `ReadOnlyEntry`
4. `EntryList`
5. `Event`, `Deadline`, `FloatingTask`

You may even merge the `V0.3_model_implementation` branch into yours to see if it integrates well or not.
